[package]
name = "flux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atlas = { path = "../atlas" }
macros = { path = "../macros" }
glad-gl = {path="../glad-gl"}
glam = "0.24.0"
