[package]
name = "atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.51.0"
glad-gl = {path="../glad-gl"}
vertex_macro_derive  = {path="../vertex_macro_derive"}
glam = "0.24.0"
image = "0.24.6"
gltf = "1.1.0"
freetype-rs = "0.32.0"
rand = "0.8.5"
